### PR TITLE
Fix hsl2rgb implementation

### LINKED ISSUE #2: Wrong implementation for hsv2rgb
## Expected

```js
expect( hsv2rgb(123, 37, 60) ).toEqual( [96, 153, 99].map(val => val / 255 * 100) )
```

53f1c857c8d2487914eaaf3d7

## Actual

```js
Expected value to equal:
      [37.64705882352941, 60, 38.82352941176471]
Received:
      [37.8, 60, 127.71]
```

## Why

https://github.com/jonathantneal/convert-colors/blob/273fa68a1aecac8bf72f2dae8abeca5302d8666d/src/rgb-hsv.js#L44-L54

image

Wiki pages which are both in [Chinese](https://zh.wikipedia.org/wiki/HSL%E5%92%8CHSV%E8%89%B2%E5%BD%A9%E7%A9%BA%E9%97%B4#%E4%BB%8EHSV%E5%88%B0RGB%E7%9A%84%E8%BD%AC%E6%8D%A2) and [German](https://de.wikipedia.org/wiki/HSV-Farbraum#Umrechnung_HSV_in_RGB) are more comprehensible than the english one.

### PR DESCRIPTION
**Pull request by jonathantneal**
Resolves #2

If I understand correctly, the [Chinese](https://zh.wikipedia.org/wiki/HSL%E5%92%8CHSV%E8%89%B2%E5%BD%A9%E7%A9%BA%E9%97%B4#%E4%BB%8EHSV%E5%88%B0RGB%E7%9A%84%E8%BD%AC%E6%8D%A2) and [German](https://de.wikipedia.org/wiki/HSV-Farbraum#Umrechnung_HSV_in_RGB) equations are more comprehensible than the [English](https://en.wikipedia.org/wiki/HSL_and_HSV#From_HSV) one, which had led me to incorrectly calculate HSL to RGB conversions.

### CODE REVIEW

File: src/rgb-hsv.js [hunk 1]
```diff
@@ -43,18 +43,19 @@ export function hsv2rgb(hsvH, hsvS, hsvV) {
 	const rgbF = hsvH / 60 - rgbI & 1 ? hsvH / 60 - rgbI : 1 - hsvH / 60 - rgbI;
```
Comment (599316527) [inline src/rgb-hsv.js]: The inequation `hsvH / 60 >= floor(hsvH / 60)` is always true. It's not necessary to consider a negative value.

File: src/rgb-hsv.js [hunk 2]
```diff
@@ -43,18 +43,19 @@ export function hsv2rgb(hsvH, hsvS, hsvV) {
...
 	const rgbM = hsvV * (100 - hsvS) / 100;
 	const rgbN = hsvV * (100 - hsvS * rgbF) / 100;
+	const rgbT = hsvV * (100 - (100 - rgbF) * hsvS / 100) / 100;
```
Comment (599316527) [inline src/rgb-hsv.js]: Shall be `hsvV * (1 - (1 - rgbF) * (hsvS / 100))`? 
`rgbF` shall not be divided by 100?

**Comment by jonathantneal** [comment]
@599316527, I’ve been busy with some things. Would you be available to write the final fixes? You could even use the `suggestion` syntax (https://help.github.com/en/articles/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request) to suggest the changes as a comment.
